<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo $title; ?></title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #0041c3;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #0041c3;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            color: #666;
            margin: 5px 0;
        }
        .section {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .section h2 {
            color: #0041c3;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
            font-size: 18px;
            margin-bottom: 15px;
        }
        .metrics-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
            border-collapse: collapse;
        }
        .metric-item {
            display: table-cell;
            width: 25%;
            text-align: center;
            padding: 15px;
            border: 1px solid #ddd;
        }
        .metric-value {
            font-size: 24px;
            font-weight: bold;
            color: #0041c3;
        }
        .metric-label {
            font-size: 14px;
            color: #666;
        }
        .payment-methods {
            margin-top: 20px;
        }
        .payment-item {
            display: table;
            width: 100%;
            margin-bottom: 10px;
            border: 1px solid #ddd;
            border-collapse: collapse;
        }
        .payment-label {
            display: table-cell;
            width: 30%;
            padding: 10px;
            font-weight: bold;
            border: 1px solid #ddd;
        }
        .payment-value {
            display: table-cell;
            width: 20%;
            padding: 10px;
            text-align: center;
            font-weight: bold;
            color: #0041c3;
            border: 1px solid #ddd;
        }
        .progress-bar {
            display: table-cell;
            width: 50%;
            padding: 10px;
            border: 1px solid #ddd;
        }
        .progress-bg {
            height: 20px;
            background: #f0f0f0;
            border-radius: 10px;
            overflow: hidden;
        }
        .progress-fill {
            height: 100%;
            background: linear-gradient(90deg, #0041c3, #3366d6);
            border-radius: 10px;
        }
        .summary {
            background: #f9f9f9;
            padding: 15px;
            border-radius: 5px;
            margin-top: 20px;
            border: 1px solid #ddd;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }

        /* Print styles */
        @media print {
            body {
                margin: 0;
                font-size: 12px;
            }
            .header {
                margin-bottom: 20px;
            }
            .section {
                margin-bottom: 20px;
            }
            .no-print {
                display: none;
            }
        }

        /* Print button */
        .print-btn {
            position: fixed;
            top: 20px;
            right: 20px;
            background: #0041c3;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
        }
        .print-btn:hover {
            background: #003399;
        }
    </style>
</head>
<body>
    <button class="print-btn no-print" onclick="window.print()">🖨️ Print Report</button>

    <div class="header">
        <h1>AZZAHRA COMPUTER - Dashboard Report</h1>
        <p><?php echo date('l, d F Y H:i:s'); ?></p>
        <p>Generated by: <?php echo $this->session->userdata('nama'); ?></p>
    </div>

    <?php if ($export_section == 'all' || $export_section == 'performance'): ?>
    <div class="section">
        <h2>Performance Metrics</h2>
        <div class="metrics-grid">
            <div class="metric-item">
                <div class="metric-value">Rp <?php echo number_format($revenue_today, 0, ',', '.'); ?></div>
                <div class="metric-label">Revenue Today</div>
            </div>
            <div class="metric-item">
                <div class="metric-value"><?php echo $service_completion_rate; ?></div>
                <div class="metric-label">Pembayaran Lunas</div>
            </div>
            <div class="metric-item">
                <div class="metric-value"><?php echo $total_customers; ?></div>
                <div class="metric-label">Total Customers</div>
            </div>
            <div class="metric-item">
                <div class="metric-value"><?php echo $dp_pending; ?></div>
                <div class="metric-label">Pembayaran DP</div>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <?php if ($export_section == 'all' || $export_section == 'payment'): ?>
    <div class="section">
        <h2>Payment Methods Overview</h2>
        <div class="payment-methods">
            <?php if (!empty($bank_percentages)): ?>
                <?php
                $bca_pct = isset($bank_percentages['BCA']) ? $bank_percentages['BCA'] : 0;
                $mandiri_pct = isset($bank_percentages['MANDIRI']) ? $bank_percentages['MANDIRI'] : 0;
                $bri_pct = isset($bank_percentages['BRI']) ? $bank_percentages['BRI'] : 0;
                ?>

                <div class="payment-item">
                    <div class="payment-label">Bank BCA</div>
                    <div class="payment-value"><?php echo $bca_pct; ?>%</div>
                    <div class="progress-bar">
                        <div class="progress-bg">
                            <div class="progress-fill" style="width: <?php echo $bca_pct; ?>%;"></div>
                        </div>
                    </div>
                </div>

                <div class="payment-item">
                    <div class="payment-label">Bank Mandiri</div>
                    <div class="payment-value"><?php echo $mandiri_pct; ?>%</div>
                    <div class="progress-bar">
                        <div class="progress-bg">
                            <div class="progress-fill" style="width: <?php echo $mandiri_pct; ?>%;"></div>
                        </div>
                    </div>
                </div>

                <div class="payment-item">
                    <div class="payment-label">Bank BRI</div>
                    <div class="payment-value"><?php echo $bri_pct; ?>%</div>
                    <div class="progress-bar">
                        <div class="progress-bg">
                            <div class="progress-fill" style="width: <?php echo $bri_pct; ?>%;"></div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

            <div class="payment-item">
                <div class="payment-label">Tunai</div>
                <div class="payment-value"><?php echo $tunai_percentage; ?>%</div>
                <div class="progress-bar">
                    <div class="progress-bg">
                        <div class="progress-fill" style="width: <?php echo $tunai_percentage; ?>%;"></div>
                    </div>
                </div>
            </div>

            <div class="payment-item">
                <div class="payment-label">Payment Pending</div>
                <div class="payment-value"><?php echo $total_pending_transfers; ?></div>
                <div class="progress-bar">
                    <div class="progress-bg">
                        <div class="progress-fill" style="width: 100%;"></div>
                    </div>
                </div>
            </div>

            <div class="payment-item">
                <div class="payment-label">Voucher Used</div>
                <div class="payment-value"><?php echo $voucher_usage_percentage; ?>%</div>
                <div class="progress-bar">
                    <div class="progress-bg">
                        <div class="progress-fill" style="width: <?php echo $voucher_usage_percentage; ?>%;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <?php if ($export_section == 'all' || $export_section == 'weekly'): ?>
    <div class="section">
        <h2>Weekly Performance</h2>
        <div class="summary">
            <?php
            $period_text = 'Last 7 Days';
            if (isset($weekly_period)) {
                switch($weekly_period) {
                    case '1M': $period_text = 'Last 30 Days'; break;
                    case '3M': $period_text = 'Last 90 Days'; break;
                    case '1Y': $period_text = 'Last 365 Days'; break;
                    default: $period_text = 'Last 7 Days';
                }
            }
            ?>
            <?php if (!empty($weekly_revenue)): ?>
                <h3>Revenue Performance (<?php echo $period_text; ?>)</h3>
                <?php
                // Group revenue data by month
                $revenue_by_month = [];
                foreach ($weekly_revenue as $row) {
                    $month_key = date('Y-m', strtotime($row['day']));
                    $month_name = date('F Y', strtotime($row['day']));
                    if (!isset($revenue_by_month[$month_key])) {
                        $revenue_by_month[$month_key] = ['name' => $month_name, 'data' => []];
                    }
                    $revenue_by_month[$month_key]['data'][] = $row;
                }
                ksort($revenue_by_month); // Sort by month
                ?>

                <?php foreach ($revenue_by_month as $month_data): ?>
                    <h4 style="margin-top: 20px; margin-bottom: 10px; color: #0041c3; border-bottom: 1px solid #ddd; padding-bottom: 5px;"><?php echo $month_data['name']; ?></h4>
                    <table style="width: 100%; border-collapse: collapse; margin-bottom: 15px;">
                        <thead>
                            <tr style="background: #f0f0f0;">
                                <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Date</th>
                                <th style="border: 1px solid #ddd; padding: 8px; text-align: right;">Revenue (Rp)</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($month_data['data'] as $row): ?>
                                <tr>
                                    <td style="border: 1px solid #ddd; padding: 8px;"><?php echo date('D, d M Y', strtotime($row['day'])); ?></td>
                                    <td style="border: 1px solid #ddd; padding: 8px; text-align: right;"><?php echo number_format($row['total'], 0, ',', '.'); ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if (!empty($weekly_transactions)): ?>
                <h3>Transaction Performance (<?php echo $period_text; ?>)</h3>
                <?php
                // Group transaction data by month
                $transactions_by_month = [];
                foreach ($weekly_transactions as $row) {
                    $month_key = date('Y-m', strtotime($row['day']));
                    $month_name = date('F Y', strtotime($row['day']));
                    if (!isset($transactions_by_month[$month_key])) {
                        $transactions_by_month[$month_key] = ['name' => $month_name, 'data' => []];
                    }
                    $transactions_by_month[$month_key]['data'][] = $row;
                }
                ksort($transactions_by_month); // Sort by month
                ?>

                <?php foreach ($transactions_by_month as $month_data): ?>
                    <h4 style="margin-top: 20px; margin-bottom: 10px; color: #0041c3; border-bottom: 1px solid #ddd; padding-bottom: 5px;"><?php echo $month_data['name']; ?></h4>
                    <table style="width: 100%; border-collapse: collapse; margin-bottom: 15px;">
                        <thead>
                            <tr style="background: #f0f0f0;">
                                <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Date</th>
                                <th style="border: 1px solid #ddd; padding: 8px; text-align: right;">Transactions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($month_data['data'] as $row): ?>
                                <tr>
                                    <td style="border: 1px solid #ddd; padding: 8px;"><?php echo date('D, d M Y', strtotime($row['day'])); ?></td>
                                    <td style="border: 1px solid #ddd; padding: 8px; text-align: right;"><?php echo $row['total']; ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if (!empty($weekly_customers)): ?>
                <h3>New Customers (<?php echo $period_text; ?>)</h3>
                <?php
                // Group customer data by month
                $customers_by_month = [];
                foreach ($weekly_customers as $row) {
                    $month_key = date('Y-m', strtotime($row['day']));
                    $month_name = date('F Y', strtotime($row['day']));
                    if (!isset($customers_by_month[$month_key])) {
                        $customers_by_month[$month_key] = ['name' => $month_name, 'data' => []];
                    }
                    $customers_by_month[$month_key]['data'][] = $row;
                }
                ksort($customers_by_month); // Sort by month
                ?>

                <?php foreach ($customers_by_month as $month_data): ?>
                    <h4 style="margin-top: 20px; margin-bottom: 10px; color: #0041c3; border-bottom: 1px solid #ddd; padding-bottom: 5px;"><?php echo $month_data['name']; ?></h4>
                    <table style="width: 100%; border-collapse: collapse; margin-bottom: 15px;">
                        <thead>
                            <tr style="background: #f0f0f0;">
                                <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Date</th>
                                <th style="border: 1px solid #ddd; padding: 8px; text-align: right;">New Customers</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($month_data['data'] as $row): ?>
                                <tr>
                                    <td style="border: 1px solid #ddd; padding: 8px;"><?php echo date('D, d M Y', strtotime($row['day'])); ?></td>
                                    <td style="border: 1px solid #ddd; padding: 8px; text-align: right;"><?php echo $row['total']; ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>

    <?php if ($export_section == 'all' || $export_section == 'technicians'): ?>
    <div class="section">
        <h2>Top Performers Teknisi</h2>
        <div class="summary">
            <?php
            $tech_period_text = 'Last 7 Days';
            if (isset($technician_period)) {
                switch($technician_period) {
                    case '1M': $tech_period_text = 'Last 30 Days'; break;
                    case '1Y': $tech_period_text = 'Last 365 Days'; break;
                    case 'All': $tech_period_text = 'All Time'; break;
                    default: $tech_period_text = 'Last 7 Days';
                }
            }
            ?>
            <p><strong>Period:</strong> <?php echo $tech_period_text; ?></p>
            <?php if (!empty($technician_details)): ?>
                <?php
                // Group technician data by name and sum services_completed (same as dashboard chart logic)
                $techMap = [];
                foreach ($technician_details as $tech) {
                    $name = $tech['technician_name'] ?? 'Teknisi Tidak Diketahui';
                    if (!isset($techMap[$name])) {
                        $techMap[$name] = 0;
                    }
                    $techMap[$name] += $tech['services_completed'] ?? 0;
                }
                arsort($techMap); // Sort by services completed descending

                // Get top 10 performers
                $topTechnicians = array_slice($techMap, 0, 10, true);
                ?>
                <table style="width: 100%; border-collapse: collapse;">
                    <thead>
                        <tr style="background: #f0f0f0;">
                            <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Rank</th>
                            <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Technician Name</th>
                            <th style="border: 1px solid #ddd; padding: 8px; text-align: right;">Services Completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $rank = 1;
                        foreach ($topTechnicians as $techName => $servicesCompleted):
                        ?>
                            <tr>
                                <td style="border: 1px solid #ddd; padding: 8px; text-align: center; font-weight: bold;"><?php echo $rank; ?></td>
                                <td style="border: 1px solid #ddd; padding: 8px;"><?php echo htmlspecialchars($techName); ?></td>
                                <td style="border: 1px solid #ddd; padding: 8px; text-align: right;"><?php echo $servicesCompleted; ?></td>
                            </tr>
                        <?php
                            $rank++;
                        endforeach;
                        ?>
                    </tbody>
                </table>
            <?php else: ?>
                <p>No technician performance data available.</p>
            <?php endif; ?>
        </div>
    </div>

<?php endif; ?>

    <?php if ($export_section == 'all' || $export_section == 'activity'): ?>
    <div class="section">
        <h2>Recent Activity Details</h2>
        <div class="summary">
            <h3>Recent Customers (Last Activity)</h3>
            <?php if ($baru->num_rows() > 0): ?>
                <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
                    <thead>
                        <tr style="background: #f0f0f0;">
                            <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Customer Name</th>
                            <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Activity</th>
                            <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Time</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($baru->result_array() as $row): ?>
                            <tr>
                                <td style="border: 1px solid #ddd; padding: 8px;"><?php echo html_escape($row['cos_nama']); ?></td>
                                <td style="border: 1px solid #ddd; padding: 8px;">Customer baru dikonfirmasi</td>
                                <td style="border: 1px solid #ddd; padding: 8px;"><?php echo html_escape($row['cos_jam']); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else: ?>
                <p>No recent customer activity.</p>
            <?php endif; ?>

            <h3>Recent Users (Last Activity)</h3>
            <?php if ($users_baru->num_rows() > 0): ?>
                <table style="width: 100%; border-collapse: collapse;">
                    <thead>
                        <tr style="background: #f0f0f0;">
                            <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">User Name</th>
                            <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Activity</th>
                            <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Time</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($users_baru->result_array() as $row): ?>
                            <tr>
                                <td style="border: 1px solid #ddd; padding: 8px;"><?php echo html_escape($row['cos_nama']); ?></td>
                                <td style="border: 1px solid #ddd; padding: 8px;">User baru terdaftar</td>
                                <td style="border: 1px solid #ddd; padding: 8px;"><?php echo html_escape($row['cos_jam']); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else: ?>
                <p>No recent user activity.</p>
            <?php endif; ?>
        </div>
    </div>

    <div class="section">
        <h2>Activity Summary</h2>
        <div class="summary">
            <p><strong>Konfirmasi Pending:</strong> <?php echo $konf->num_rows(); ?> transaksi menunggu konfirmasi</p>
            <p><strong>Voucher Aktif:</strong> <?php echo $discount->num_rows(); ?> voucher tersedia</p>
            <p><strong>Customer Baru Hari Ini:</strong> <?php echo $baru->num_rows(); ?> customer</p>
            <p><strong>User Baru Hari Ini:</strong> <?php echo $users_baru->num_rows(); ?> user</p>
        </div>
    </div>
    <?php endif; ?>

    <div class="footer">
        <p>Report generated on <?php echo date('d F Y H:i:s'); ?> by Azzahra Computer Management System</p>
        <p>This report contains confidential business information</p>
    </div>
</body>
</html>